# Generated by Django 5.2.8 on 2025-11-24 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_notebook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='notebook_files/'),
        ),
        migrations.AlterField(
            model_name='source',
            name='content',
            field=models.TextField(blank=True, help_text='Paste text or leave blank if uploading a file.', null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='source_type',
            field=models.CharField(choices=[('text', 'Text'), ('url', 'URL'), ('file', 'File Upload')], default='text', max_length=10),
        ),
    ]
