# Generated by Django 5.2.8 on 2025-11-24 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_notebook', '0002_source_file_alter_source_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='source_type',
            field=models.CharField(choices=[('text', 'Text'), ('url', 'URL'), ('file', 'File Upload')], max_length=10),
        ),
    ]
