# Generated by Django 5.2.8 on 2025-11-24 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_notebook', '0003_source_url_alter_source_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='content',
            field=models.TextField(blank=True, help_text='Text content of this source (pasted or auto-extracted).', null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='source_type',
            field=models.CharField(choices=[('text', 'Text'), ('url', 'URL'), ('file', 'File')], default='text', max_length=10),
        ),
    ]
