# Generated by Django 5.2.8 on 2025-11-24 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_notebook', '0004_alter_source_content_alter_source_source_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='source',
            options={'ordering': ['position', '-created_at']},
        ),
        migrations.AddField(
            model_name='source',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='source',
            name='content',
            field=models.TextField(blank=True, help_text='Text content of this source (pasted OR extracted).', null=True),
        ),
    ]
