# Generated by Django 5.2.8 on 2025-11-24 15:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='requested_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscription',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='payments/'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='payment_ref',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
